version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      
  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - .data/redis:/data
    
  subql-cardano:
    # image: cuonglv0297/subql-cardano:v1.0.0-non-mithril
    build:
      context: ../../..
      dockerfile: ./packages/node/Dockerfile
      # dockerfile: ./
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379
    # volumes:
    #   - ./data/app:/app
    # command:
    #   - ${SUB_COMMAND:-} # set SUB_COMMAND env variable to "test" to run tests
    #   - -f=/app
    #   - --db-schema=app
    #   - --workers=4
    #   - --batch-size=30
    #   - --unfinalized-blocks=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-cardano:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10
    
  graphql-engine:
    image: subquerynetwork/subql-query:latest
    ports:
      - 3000:3000
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
    network_mode: host
    command:
      - --name=cardano-ibc
      - --playground
      - --indexer=http://subql-cardano:3001
