version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  
  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - ./data/redis:/data
