services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - .data/redis:/data

  subql-cardano:
    container_name: subql-cardano
    image: cuonglv0297/subql-node-cardano:latest
    # build:
    #   context: ..
    #   dockerfile: ./packages/node/Dockerfile
    # depends_on:
    #   "postgres":
    #     condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379

    volumes:
      - ../packages/cardano-ibc:/app/packages/cardano-ibc
    command:
      - yarn # set SUB_COMMAND env variable to "test" to run tests
      - start:dev
      - --multi-chain
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://subql-query:3000/ready"
        ]
      interval: 3s
      timeout: 5s
      retries: 10
    ports:
      - 3001:3001

  graphql-engine:
    image: subquerynetwork/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subql-cardano":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=cardano-ibc
      - --playground
      - --indexer=http://subql-cardano:3001
